---
nodes:
- name: input_0
  node_type: input_file
  path: samples/sample_01.wav
  looping: false
- name: normalizer_input_0
  node_type: normalizer
  headroom: 3.75
- name: resampler_input_0
  node_type: resampler
  to_rate: 16000
- name: converter_0
  node_type: converter_seamless
  server_url: http://127.0.0.1:8000
  lang_from: ru
  lang_to: en
- name: output_channel_1
  node_type: output_channel
  device: 14 # <-- This device should be set for audio output
  channel: 1 # <-- Always set to 1 for audio output
- name: output_file_0
  node_type: output_file
  path: mic_input.wav
- name: output_file_1
  node_type: output_file
  path: mic_output.wav
- name: resampler_output_1
  node_type: resampler
  to_rate: 44100 # <-- !!! resampler_output_1 rate
edges:
- [input_0, normalizer_input_0]
- [normalizer_input_0, resampler_input_0]
- [resampler_input_0, converter_0]
- [converter_0, resampler_output_1]
- [resampler_output_1, output_file_1]
- [resampler_input_0, output_file_0]
