---
nodes:
- name: input_mic_0_en
  node_type: input_channel
  device: 0 # <-- This device should be set for microphone input
  channel: 1 # <-- Always set to 1 for microphone input
  stream:
    language: en
    audio_format:
      format_type: int16
    rate: 44100 # <-- This rate is desirable but optional, only for the sake of clarity
- name: resampler_input_0_en
  node_type: resampler
  to_rate: 16000
- name: converter_0_en_ru
  node_type: converter_seamless
  server_url: http://127.0.0.1:8000
  lang_from: en
  lang_to: ru
- name: output_file_mic
  node_type: output_file
  path: samples/sample_mic_input.wav
  stream:
    language: ru
    audio_format:
      format_type: int16
    rate: 16000
- name: output_file_1_ru
  node_type: output_file
  path: samples/sample_mic_output.wav
  stream:
    language: ru
    audio_format:
      format_type: int16
    rate: 44100 # <-- !!! Must be equal to resampler_output_1 rate
- name: output_channel_1_ru
  node_type: output_channel
  device: 1 # <-- This device should be set for audio output
  channel: 1 # <-- Always set to 1 for audio output
  stream:
    language: ru
    audio_format:
      format_type: int16
    rate: 44100 # <-- !!! Must be equal to resampler_output_1 rate
- name: resampler_output_1
  node_type: resampler
  to_rate: 44100 # <-- !!! resampler_output_1 rate
edges:
- - input_mic_0_en
  - resampler_input_0_en
- - resampler_output_1
  - output_file_1_ru
- - resampler_output_1
  - output_channel_1_ru
- - converter_0_en_ru
  - resampler_output_1
- - resampler_input_0_en
  - converter_0_en_ru
- - resampler_input_0_en
  - output_file_mic