---
nodes:
- name: input_mic_0_ru
  node_type: input_channel
  device: 0 # <-- This device should be set for microphone input
  channel: 1 # <-- Always set to 1 for microphone input
- name: resampler_input_0_ru
  node_type: resampler
  to_rate: 16000
- name: converter_0
  node_type: converter_seamless
  server_url: http://127.0.0.1:8000Ñ‹
  lang_from: ru
  lang_to: en
- name: output_file_mic
  node_type: output_file
  path: samples/sample_mic_input.wav
- name: output_file_1_en
  node_type: output_file
  path: samples/sample_mic_output.wav
- name: output_channel_1_en
  node_type: output_channel
  device: 1 # <-- This device should be set for audio output
  channel: 1 # <-- Always set to 1 for audio output
- name: resampler_output_1
  node_type: resampler
  to_rate: 44100 # <-- !!! resampler_output_1 rate
edges:
- - input_mic_0_ru
  - resampler_input_0_ru
- - resampler_output_1
  - output_file_1_en
- - resampler_output_1
  - output_channel_1_en
- - converter_0
  - resampler_output_1
- - resampler_input_0_ru
  - converter_0
- - resampler_input_0_ru
  - output_file_mic