---
nodes:
- name: input_file_0_en
  node_type: input_file
  path: samples/sample_01.wav
  stream:
    language: en
    audio_format:
      format_type: int16
    rate: 22050
  looping: false
  delay_ms: 0
- name: normalizer_input_0_en
  node_type: normalizer
  headroom: 5.0
- name: resampler_input_0_en
  node_type: resampler
  to_rate: 16000
- name: converter_0_en_ru
  node_type: converter_seamless
  server_url: http://127.0.0.1:8000
  lang_from: en
  lang_to: ru
- name: output_file_source
  node_type: output_file
  path: samples/source_input.wav
  stream:
    language: ru
    audio_format:
      format_type: int16
    rate: 16000
- name: output_file_1_ru
  node_type: output_file
  path: samples/translated_output.wav
  stream:
    language: ru
    audio_format:
      format_type: int16
    rate: 44100
- name: resampler_output_1
  node_type: resampler
  to_rate: 44100
edges:
- - input_file_0_en
  - normalizer_input_0_en
- - normalizer_input_0_en
  - resampler_input_0_en
- - resampler_input_0_en
  - converter_0_en_ru
- - converter_0_en_ru
  - resampler_output_1
- - resampler_output_1
  - output_file_1_ru
- - resampler_input_0_en
  - output_file_source