---
nodes:
- name: input_file_0_ru
  node_type: input_file
  path: samples/sample_01.wav
  stream:
    language: ru
    audio_format:
      format_type: int16
    rate: 22050
  looping: false
  delay_ms: 0
- name: resampler_input_0_ru
  node_type: resampler
  to_rate: 16000
- name: converter_0_ru_en
  node_type: converter_seamless
  server_url: http://127.0.0.1:8000
  lang_from: ru
  lang_to: en
- name: output_file_mic
  node_type: output_file
  path: samples/sample_01_input.wav
  stream:
    language: en
    audio_format:
      format_type: int16
    rate: 16000
- name: output_file_1_en
  node_type: output_file
  path: samples/sample_01_output.wav
  stream:
    language: en
    audio_format:
      format_type: int16
    rate: 44100
- name: resampler_output_1
  node_type: resampler
  to_rate: 44100
- name: mixer_1_en
  node_type: mixer
edges:
- - input_file_0_ru
  - resampler_input_0_ru
- - resampler_output_1
  - output_file_1_en
- - mixer_1_en
  - resampler_output_1
- - converter_0_ru_en
  - mixer_1_en
- - resampler_input_0_ru
  - converter_0_ru_en
- - resampler_input_0_ru
  - output_file_mic