---
nodes:
- name: input_file_0_ru
  node_type: input_file
  path: samples/test_hfc_male.wav
  looping: false
- name: normalizer_input_0_ru
  node_type: normalizer
  headroom: 3.75
- name: resampler_input_0_ru
  node_type: resampler
  to_rate: 16000
- name: converter_0
  node_type: converter_seamless
  server_url: http://127.0.0.1:8000
  lang_from: ru
  lang_to: en
- name: output_file_mic
  node_type: output_file
  path: samples/source_input.wav
- name: output_file_1_en
  node_type: output_file
  path: samples/translated_output.wav
- name: resampler_output_1
  node_type: resampler
  to_rate: 44100
edges:
- - input_file_0_ru
  - normalizer_input_0_ru
- - normalizer_input_0_ru
  - resampler_input_0_ru
- - resampler_input_0_ru
  - converter_0
- - converter_0
  - resampler_output_1
- - resampler_output_1
  - output_file_1_en
- - resampler_input_0_ru
  - output_file_mic
