defaults:
  - ai: default
  - pipeline: sample_01_file
  - settings: sample_01_file
  - _self_
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe
  - override hydra/launcher: joblib
  - override hydra/job_logging: custom
hydra:
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    sampler:
      seed: 777
    direction: maximize
    study_name: sample_01
    n_trials: 24
    n_jobs: 6
    params:
      ai.stt.buffer_min_words_size: range(2, 8)
      ai.stt.buffer_timeout_seconds: range(0.5, 4, step=0.25)
      ai.translate.context_window: range(2, 8)
      ai.translate.gate_template: ''
      ai.translate.correction_template: choice('', 'file://config/ai/correction_query_1.txt')
      ai.translate.text_template: choice('file://config/ai/text_query_1.txt', 'file://config/ai/text_query_2.txt')

