name: Default_RU_EN
limits:
  run_time_seconds: 15  # <-- Set 0 for unlimited time
metrics:
  quality:
  - node: converter_0
    expected_transcription: "
    Вниманию всех пассажиров,
    поезд до города Нью-Йорка отправится с площадки 5 через 10 минут.
    Пожалуйста, убедитесь, что у вас есть все необходимые вещи
    с собой перед посадкой.
    "
    expected_translation: "
    Attention all passengers,
    the train to New York City will be departing from platform 5 in 10 minutes.
    Please ensure you have all your belongings with you before boarding.
    "
