limits:
  run_time_seconds: 20
experiments:
  bleu:
  - node: converter_0_en_ru
    expected_transcription: "
    Attention all passengers, 
    the train to New York City will be departing from platform 5 in 10 minutes. 
    Please ensure you have all your belongings with you before boarding. 
    "
    expected_translation: "
    Вниманию всех пассажиров, 
    поезд до города Нью-Йорка отправится с площадки 5 через 10 минут. 
    Пожалуйста, убедитесь, что у вас есть все необходимые вещи 
    с собой перед посадкой. 
    "