limits:
  run_time_seconds: 15
experiments:
  bleu:
  - node: converter_0_en_ru
    expected_text: "
    Вниманию всех пассажиров, 
    поезд до города Нью-Йорка отправится с площадки 5 через 10 минут. 
    пожалуйста, убедитесь, что у вас все необходимые документы вещи с собой перед посадкой. 
    Вниманию всех пассажиров, поезд в город Нью-Йорк от аэропорта отправится с 
    платформы 5 через 10 минут.
    "