name: Sample RU->EN
input_interval_secs: 0.3
processor_interval_secs: 0.016
limits:
  run_time_seconds: 30  # <-- Set 0 for unlimited time
metrics:
  quality:
  - node: converter_0
    expected_transcription: ""
    expected_translation: ""
