limits:
  run_time_seconds: 90
experiments:
  bleu:
  - node: converter_0_ru_en
    expected_transcription: "Просто нету практики взаимодействия с инвалидами. Мало 
    здоровые люди общаются, мало практикуют, сотрудничают с ними, и поэтому они 
    просто теряются и не знают, как себя вести. И, к сожалению, так как большинство
    инвалидов закрыты дома, вы не видите, что они могут быть успешными людьми, могут 
    заказывать тур на свои деньги, могут зарабатывать, могут строить карьеру, свою семью…
    И вот это ломает. И зарождается много комплексов, комплекс неполноценности, когда 
    инвалид не хочет, чтобы с ними говорили, потому что он не хочет быть во втором лице. 
    Но что можно сделать? Как можно изменить ситуацию? Я уверен, вы знаете, что есть 
    исключения. Есть такие инвалиды, которые смогли бросить вызов своей судьбе и вопреки 
    всему, и вопреки своему здоровью найти своё достойное место под солнцем. Есть такие 
    люди с тяжёлой инвалидностью? Я уверен, вы все знаете Ника Вуйчича, который родился 
    без рук и ног, но стал мегапопулярным оратором, отцом, мужем."
    expected_translation: "
    There is simply no practice of interacting with people with disabilities. 
    Few healthy people interact with them, practice or cooperate with them, 
    and therefore they simply get lost and don't know how to behave. They can 
    be successful people, they can order tours for their own money, they can earn, 
    they can build a career, their family... and that's what breaks it. I am sure 
    you know that there are exceptions. There are such disabled people who have 
    been able to challenge their destiny and against all odds, and against all odds, 
    to find their dignity. I'm sure you all know Nick Vucic, who was born without 
    arms and legs, but became a popular speaker, father, husband.
    "